-- Coffee Maker Pro baseline schema.
-- This migration is intentionally self-contained so a future, brand-new
-- Supabase project can be provisioned with `supabase db push`.

create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.orders_cod (
  id uuid primary key default gen_random_uuid(),
  full_name text not null check (char_length(btrim(full_name)) between 3 and 120),
  email text not null check (
    email = lower(email)
    and char_length(email) <= 320
    and email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
  ),
  phone text not null check (char_length(regexp_replace(phone, '[^0-9]', '', 'g')) between 10 and 15),
  city text not null check (char_length(btrim(city)) between 1 and 120),
  address text not null check (char_length(btrim(address)) between 3 and 300),
  total_price integer not null default 490000 check (total_price = 490000),
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.leads (
  id uuid primary key default gen_random_uuid(),
  email text not null unique check (
    email = lower(email)
    and char_length(email) <= 320
    and email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
  ),
  source text not null default 'ebook_barista_guide' check (source in ('ebook_barista_guide')),
  created_at timestamptz not null default now()
);

create table public.chat_sessions (
  id uuid primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.chat_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.chat_sessions(id) on delete cascade,
  role text not null check (role in ('user', 'model')),
  content text not null check (char_length(btrim(content)) between 1 and 8000),
  created_at timestamptz not null default now()
);

create index orders_cod_email_created_at_idx on public.orders_cod (email, created_at desc);
create index chat_messages_session_created_at_idx on public.chat_messages (session_id, created_at);

create function private.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger orders_cod_set_updated_at
before update on public.orders_cod
for each row execute function private.set_updated_at();

create trigger chat_sessions_set_updated_at
before update on public.chat_sessions
for each row execute function private.set_updated_at();

alter table public.orders_cod enable row level security;
alter table public.leads enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;

-- Public checkout: a visitor may only create a new, pending order at the
-- fixed advertised price. Existing rows cannot be read or changed anonymously.
create policy "visitors_can_create_pending_orders"
on public.orders_cod
for insert
to anon, authenticated
with check (status = 'pending' and total_price = 490000);

-- Signed-in customers can only read orders matching the verified email claim
-- in their Supabase Auth JWT. No user-editable metadata is used for access.
create policy "customers_can_read_their_orders"
on public.orders_cod
for select
to authenticated
using (
  (select auth.uid()) is not null
  and email = lower((select auth.jwt() ->> 'email'))
);

create policy "visitors_can_subscribe"
on public.leads
for insert
to anon, authenticated
with check (source = 'ebook_barista_guide');

create policy "visitors_can_create_chat_sessions"
on public.chat_sessions
for insert
to anon, authenticated
with check (true);

create policy "visitors_can_add_chat_messages"
on public.chat_messages
for insert
to anon, authenticated
with check (role in ('user', 'model'));

-- The 2026 Supabase default no longer exposes new tables automatically.
-- Grant only the columns and operations required by the application.
revoke all on table public.orders_cod from anon, authenticated;
revoke all on table public.leads from anon, authenticated;
revoke all on table public.chat_sessions from anon, authenticated;
revoke all on table public.chat_messages from anon, authenticated;

grant insert (full_name, email, phone, city, address, total_price, status)
  on table public.orders_cod to anon, authenticated;
grant select on table public.orders_cod to authenticated;
grant insert (email, source) on table public.leads to anon, authenticated;
grant insert (id) on table public.chat_sessions to anon, authenticated;
grant insert (session_id, role, content) on table public.chat_messages to anon, authenticated;
grant usage, select on sequence public.chat_messages_id_seq to anon, authenticated;
