-- CRM y métricas.
--
-- Tres bloques:
--
-- 1. `order_status_events`. Hasta ahora un pedido solo guardaba `updated_at`,
--    de modo que no había forma de saber cuándo se confirmó, cuándo salió ni
--    quién lo movió. Ese dato **no se puede reconstruir hacia atrás**: si no
--    empieza a registrarse ahora, la historia se pierde. Por eso entra aunque
--    la página de tiempos de operación no esté en el alcance actual.
--
-- 2. `contacts` y `contact_notes`. El CRM necesita una entidad por persona, no
--    por pedido, y tiene que poder existir antes de la primera compra: un
--    prospecto que escribió por WhatsApp todavía no tiene pedido. Un trigger
--    vincula cada pedido con su contacto y lo crea si hace falta, sea cual sea
--    el canal por el que entró.
--
-- 3. Vistas de métricas. PostgREST no agrega sin ayuda, y traerse todas las
--    filas al servidor para contarlas en JavaScript no aguanta el crecimiento.
--    Las vistas usan `security_invoker`, así que siguen aplicando las políticas
--    de `orders_cod`: un administrador ve todo y un comprador solo lo suyo.

-- ---------------------------------------------------------------------------
-- Historial de estados
-- ---------------------------------------------------------------------------

create table public.order_status_events (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders_cod(id) on delete cascade,
  -- Nulo en la creación del pedido: no venía de ningún estado.
  from_status text check (
    from_status is null
    or from_status in ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled')
  ),
  to_status text not null check (
    to_status in ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled')
  ),
  -- Correo del administrador que lo movió. Nulo cuando lo escribe el servidor,
  -- que es el caso de la creación desde el checkout.
  changed_by text,
  created_at timestamptz not null default now()
);

create index order_status_events_order_created_idx
  on public.order_status_events (order_id, created_at);

-- El historial lo escribe la base, no la aplicación. Así cubre los tres
-- canales de pedido y cualquier cambio hecho por SQL directo, y no hay forma
-- de mover un pedido sin dejar rastro.
create function private.record_order_status_event()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.order_status_events (order_id, from_status, to_status, changed_by)
    values (new.id, null, new.status, private.verified_email());
  elsif new.status is distinct from old.status then
    insert into public.order_status_events (order_id, from_status, to_status, changed_by)
    values (new.id, old.status, new.status, private.verified_email());
  end if;

  return new;
end;
$$;

create trigger orders_cod_record_status_event
after insert or update of status on public.orders_cod
for each row execute function private.record_order_status_event();

-- ---------------------------------------------------------------------------
-- Contactos
-- ---------------------------------------------------------------------------

create table public.contacts (
  id uuid primary key default gen_random_uuid(),
  site_id uuid not null
    default 'c0ffee00-0000-4000-8000-000000000001'
    references public.sites(id) on delete restrict,
  full_name text not null check (char_length(btrim(full_name)) between 2 and 120),
  email text check (
    email is null
    or (
      email = lower(email)
      and char_length(email) <= 320
      and email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
    )
  ),
  phone text check (
    phone is null
    or char_length(regexp_replace(phone, '[^0-9]', '', 'g')) between 10 and 15
  ),
  city text check (city is null or char_length(btrim(city)) between 1 and 120),
  -- Dónde va la conversación. `cliente` lo pone el trigger al llegar un pedido.
  stage text not null default 'nuevo' check (
    stage in ('nuevo', 'por_contactar', 'no_contesta', 'reagendar', 'cliente', 'perdido')
  ),
  -- Fecha del próximo contacto. Es lo que alimenta la bandeja de pendientes.
  next_follow_up date,
  source text not null default 'manual' check (
    source in ('pedido', 'lead', 'whatsapp', 'manual')
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- Un contacto sin ninguna forma de contactarlo no sirve para nada.
  constraint contacts_need_a_way_to_reach_them
    check (email is not null or phone is not null)
);

create trigger contacts_set_updated_at
before update on public.contacts
for each row execute function private.set_updated_at();

-- La identidad de un contacto es su correo o su celular dentro de un sitio.
-- Índices parciales porque ambos campos son opcionales.
create unique index contacts_site_email_idx
  on public.contacts (site_id, email) where email is not null;
create unique index contacts_site_phone_idx
  on public.contacts (site_id, phone) where phone is not null;

create index contacts_follow_up_idx
  on public.contacts (next_follow_up) where next_follow_up is not null;
create index contacts_stage_idx on public.contacts (site_id, stage);

create table public.contact_notes (
  id bigint generated by default as identity primary key,
  contact_id uuid not null references public.contacts(id) on delete cascade,
  body text not null check (char_length(btrim(body)) between 1 and 2000),
  author_email text not null,
  created_at timestamptz not null default now()
);

create index contact_notes_contact_created_idx
  on public.contact_notes (contact_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Vínculo entre pedido y contacto
-- ---------------------------------------------------------------------------

alter table public.orders_cod
  add column contact_id uuid references public.contacts(id) on delete set null;

create index orders_cod_contact_idx on public.orders_cod (contact_id);

-- Se resuelve en la base y no en `createOrder` para que valga igual para el
-- formulario, el chat, la voz y cualquier canal futuro.
create function private.attach_order_contact()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  existing_id uuid;
begin
  select id into existing_id
  from public.contacts
  where site_id = new.site_id
    and (
      (email is not null and email = new.email)
      or (phone is not null and phone = new.phone)
    )
  limit 1;

  if existing_id is null then
    insert into public.contacts (site_id, full_name, email, phone, city, stage, source)
    values (new.site_id, new.full_name, new.email, new.phone, new.city, 'cliente', 'pedido')
    returning id into existing_id;
  else
    -- Un prospecto que compra pasa a cliente. Se completan los huecos sin
    -- pisar lo que ya había: puede haberlo corregido una persona a mano.
    update public.contacts
    set stage = 'cliente',
        email = coalesce(email, new.email),
        phone = coalesce(phone, new.phone),
        city = coalesce(city, new.city),
        next_follow_up = null
    where id = existing_id;
  end if;

  new.contact_id := existing_id;
  return new;
end;
$$;

-- `before insert`, para poder fijar `contact_id` en la misma fila. El nombre
-- empieza por `a` a propósito: los triggers corren en orden alfabético y este
-- debe ir antes que el límite de frecuencia, que puede abortar la operación.
create trigger orders_cod_attach_contact
before insert on public.orders_cod
for each row execute function private.attach_order_contact();

-- ---------------------------------------------------------------------------
-- Vistas de métricas
-- ---------------------------------------------------------------------------

-- `security_invoker` es lo que mantiene RLS en pie: sin él la vista se
-- evaluaría con los permisos de quien la creó y cualquier usuario autenticado
-- podría leer agregados de todos los pedidos.
create view public.order_daily_stats
with (security_invoker = true) as
select
  site_id,
  -- La operación es colombiana: agrupar en UTC parte los días por la tarde.
  (created_at at time zone 'America/Bogota')::date as day,
  count(*)::int as orders,
  count(*) filter (where status = 'delivered')::int as delivered,
  count(*) filter (where status = 'cancelled')::int as cancelled,
  count(*) filter (where status in ('pending', 'confirmed', 'shipped'))::int as in_progress,
  coalesce(sum(total_price) filter (where status = 'delivered'), 0)::bigint as delivered_value
from public.orders_cod
group by site_id, 2;

-- Las ciudades las escribe el comprador a mano, así que se agrupan
-- normalizadas. Los acentos siguen separando "Medellin" de "Medellín": harían
-- falta `unaccent` y una migración aparte para resolverlo.
create view public.order_city_stats
with (security_invoker = true) as
select
  site_id,
  lower(btrim(city)) as city_key,
  initcap(lower(btrim(city))) as city,
  count(*)::int as orders,
  count(*) filter (where status = 'delivered')::int as delivered,
  count(*) filter (where status = 'cancelled')::int as cancelled,
  count(*) filter (where status in ('pending', 'confirmed', 'shipped'))::int as in_progress,
  coalesce(sum(total_price) filter (where status = 'delivered'), 0)::bigint as delivered_value
from public.orders_cod
group by site_id, 2, 3;

-- ---------------------------------------------------------------------------
-- Políticas
-- ---------------------------------------------------------------------------

alter table public.order_status_events enable row level security;
alter table public.contacts enable row level security;
alter table public.contact_notes enable row level security;

-- El comprador ve el recorrido de sus propios pedidos; el administrador, el de
-- todos. La escritura no está abierta a nadie: solo la hace el trigger.
create policy "customers_can_read_their_order_events"
on public.order_status_events
for select
to authenticated
using (
  exists (
    select 1 from public.orders_cod o
    where o.id = order_status_events.order_id
      and o.email = (select private.verified_email())
  )
);

create policy "admins_can_read_all_order_events"
on public.order_status_events
for select
to authenticated
using ((select private.is_admin()));

-- El CRM es interno. Un comprador no tiene por qué ver su propia ficha, y
-- mucho menos las notas que la operación escribe sobre él.
create policy "admins_manage_contacts"
on public.contacts
for all
to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

create policy "admins_manage_contact_notes"
on public.contact_notes
for all
to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

-- ---------------------------------------------------------------------------
-- Permisos por columna
-- ---------------------------------------------------------------------------

revoke all on table public.order_status_events from anon, authenticated;
revoke all on table public.contacts from anon, authenticated;
revoke all on table public.contact_notes from anon, authenticated;
revoke all on table public.order_daily_stats from anon, authenticated;
revoke all on table public.order_city_stats from anon, authenticated;

grant select on table public.order_status_events to authenticated;

-- El historial es un registro, no un campo editable: nadie puede reescribirlo
-- ni borrarlo desde la aplicación, ni siquiera un administrador.
grant select, insert on table public.order_status_events to service_role;

grant select on table public.contacts to authenticated;
grant insert (site_id, full_name, email, phone, city, stage, next_follow_up, source)
  on table public.contacts to authenticated;
grant update (full_name, email, phone, city, stage, next_follow_up)
  on table public.contacts to authenticated;
grant select, insert, update on table public.contacts to service_role;

grant select on table public.contact_notes to authenticated;
grant insert (contact_id, body, author_email) on table public.contact_notes to authenticated;
grant usage, select on sequence public.contact_notes_id_seq to authenticated;
grant select, insert on table public.contact_notes to service_role;
grant usage, select on sequence public.order_status_events_id_seq to service_role;

grant select on table public.order_daily_stats to authenticated;
grant select on table public.order_city_stats to authenticated;
grant select on table public.order_daily_stats to service_role;
grant select on table public.order_city_stats to service_role;

-- El servidor necesita poder fijar el vínculo al crear el pedido.
grant insert (contact_id) on table public.orders_cod to service_role;
